name: vybrnt_mvp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.6+11

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  focused_menu:
    git:
      url: https://github.com/Vybrnt-LLC/focused_menu
  hidden_drawer_menu:
    git:
      url: https://github.com/Vybrnt-LLC/hidden_drawer_menu
  image_picker:
    git:
      url: https://github.com/knaeckeKami/plugins.git
      path: packages/image_picker/image_picker
  adobe_xd: ^1.0.0+1
  animated_splash: ^1.0.0
  animated_splash_screen: ^1.0.1
  animated_text_kit: ^2.5.4
  animations: ^1.1.1
  animator: ^1.0.0+5
  async: ^2.4.0
  auto_animated: ^2.1.0
  auto_route: ^0.6.7
  auto_size_text: ^2.1.0
  bloc: ^6.0.3
  bordered_text: ^1.0.0
  cached_network_image: ^2.5.0
  cloud_firestore: ^0.14.0+2
  cupertino_icons: ^0.1.2
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  dropdown_search: ^0.4.4
  equatable: ^1.0.0
  file_picker: ^2.0.7
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.2.1
  firebase_dynamic_links: ^0.6.3
  firebase_messaging: ^7.0.3
  firebase_performance: ^0.3.2
  firebase_storage: ^4.0.0
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.5
  flutter_circle_color_picker: ^0.2.0
  flutter_datetime_picker: ^1.3.8
  flutter_hooks: ^0.10.0
  flutter_image_compress: ^0.6.3
  flutter_local_notifications: ^4.0.0
  flutter_material_color_picker: ^1.0.5
  flutter_native_timezone: ^1.0.4
  flutter_plugin_android_lifecycle: ^1.0.8
  flutter_slidable: ^0.5.4
  flutter_speed_dial: ^1.2.5
  flutter_spinkit: ^4.1.1+1
  flutter_staggered_animations: ^0.1.2
  flutter_statusbarcolor: ^0.2.3
  font_awesome_flutter: ^8.11.0
  freezed_annotation: ^0.7.1
  get_it: ^4.0.2
  getflutter: ^1.0.9
  google_fonts: ^1.1.0
  google_sign_in: ^4.5.4
  http: ^0.12.0+4
  image_cropper: ^1.2.1
  injectable: ^1.0.4
  intl: ^0.16.1
  json_annotation: ^3.0.1
  kt_dart: ^0.7.0+1
  like_button: ^1.0.4
  material_design_icons_flutter: ^3.4.4895
  meta: ^1.1.8
  mockito: ^4.1.0
  overlay_support: ^1.0.5
  page_transition: ^1.1.6
  path_provider: ^1.2.0
  provider: ^4.0.2
  provider_architecture: ^1.0.5
  reorderables: ^0.3.2
  responsive_builder: ^0.1.4
  rxdart: ^0.23.1
  share: ^0.6.5+4
  shared_preferences: ^0.5.8
  shimmer: ^1.1.2
  sign_in_with_apple: ^2.5.2
  simple_url_preview: ^1.1.0
  table_calendar: ^2.2.2
  timeago: ^2.0.26
  timezone: ^0.6.1
  truncate: ^2.1.2
  url_launcher: ^5.4.10
  uuid: ^2.0.4
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  build_runner: ^1.10.2
  flutter_launcher_icons: ^0.7.5
  freezed: ^0.10.8
  injectable_generator: ^1.0.4

  json_serializable: ^3.4.1
  lint: ^1.2.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/VYBrntfin-06.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/categories/
    - assets/gifs/
    - assets/logos/
    - config/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Socicon
      fonts:
        - asset: assets/icons/Socicon.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy-extrabold.otf
          weight: 800
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Regular.ttf
          weight: 300      

    # - family: Righteous
    #   fonts:
    #     - asset: assets/fonts/Righteous-Regular.tff
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
